### ISSUE TITLE
Startup error 'Container' object has no attribute 'description'

### ISSUE THREAD

**Issue by drubb** [lxdock/lxdock#85]
I've installed the latest versions of lxd (2.14) and lxdock (0.2.1). I'm trying to create and start a new container using a very simple lxdock.yml file:

```
name: mycontainer
image: alpine/3.5
```

This throws a error regarding a wrong container attribute:
```
Bringing container "default" up
==> default: Unable to find container "default" for directory "/home/drubb/test2"
==> default: Creating new container "mycontainer-default-2901827" from image alpine/3.5
Traceback (most recent call last):
  File "/home/drubb/.local/lib/python3.5/site-packages/pylxd/models/_model.py", line 119, in __getattribute__
    return super(Model, self).__getattribute__(name)
AttributeError: status_code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/drubb/.local/bin/lxdock", line 11, in <module>
    sys.exit(main())
  File "/home/drubb/.local/lib/python3.5/site-packages/lxdock/cli/main.py", line 244, in main
    LXDock(argv=argv)
  File "/home/drubb/.local/lib/python3.5/site-packages/lxdock/cli/main.py", line 118, in __init__
    getattr(self, args.action)(args)
  File "/home/drubb/.local/lib/python3.5/site-packages/lxdock/cli/main.py", line 210, in up
    self.project.up(container_names=args.name)
  File "/home/drubb/.local/lib/python3.5/site-packages/lxdock/project.py", line 84, in up
    container.up()
  File "/home/drubb/.local/lib/python3.5/site-packages/lxdock/container.py", line 129, in up
    if self.is_running:
  File "/home/drubb/.local/lib/python3.5/site-packages/lxdock/container.py", line 191, in is_running
    return self._container.status_code == constants.CONTAINER_RUNNING
  File "/home/drubb/.local/lib/python3.5/site-packages/pylxd/models/_model.py", line 122, in __getattribute__
    self.sync()
  File "/home/drubb/.local/lib/python3.5/site-packages/pylxd/models/_model.py", line 154, in sync
    setattr(self, key, val)
  File "/home/drubb/.local/lib/python3.5/site-packages/pylxd/models/_model.py", line 135, in __setattr__
    return super(Model, self).__setattr__(name, value)
AttributeError: 'Container' object has no attribute 'description'
```

After this, I'm able to work with the container using lxc commands, but lxdock commands keep throwing errors. E.g. here's the output from ' lxdock status':

```
Current container states:
/home/drubb/.local/lib/python3.5/site-packages/pylxd/models/_model.py:113: UserWarning: Attempted to set unknown attribute "description" on instance of "Container"
  key, self.__class__.__name__
default           (running)
```

Thanks for any advice,
Boris

**Comment by hsoft** [comment]
@drubb Thanks for reporting the issue, but we've been aware of it. pylxd is currently broken with new versions of LXD. I have a [PR waiting to be reviewed](https://github.com/lxc/pylxd/pull/234), but as I was saying to @ellmetha in #84 , we might want to temporarily point our `requirements.txt` to my own private branch rather than waiting for my PR to be merged.

**Comment by ellmetha** [comment]
The development version of `pylxd` fixes the problem too. So yes I guess a new patch could be released to fix the problem temporarily. 😉

**Comment by hsoft** [comment]
@ellmetha I haven't tried it, but while I think that pylxd's `master` will work well with LXD 2.14, I'm not sure that it will work well with older versions that don't have the `description` field.

**Comment by ellmetha** [comment]
@hsoft I was just pointing out that I noticed that the development version of `pylxd` was working with LXD 2.14. I'm OK if you release a patch that uses your branch. 😉

**Comment by hsoft** [comment]
Damn! this `pbr` thing makes it much harder to hot-swap the dependency directly to a git repo...

**Comment by hsoft** [comment]
Done. @drubb if you install lxdock from `master` (clone the repo, `cd` into it, then run `pip install --process-dependency-links --user .`), does it work well on your side?

**Comment by drubb** [comment]
Sadly, it doesn't. I'm afraid this is due to my lack of any python knowledge. I've uninstalled lxdock using pip3 uninstall, cloned the master branch, and started the build using the following command:
```
pip install -r requirements-dev.txt --process-dependency-links --user
```
(assuming I should replace the missing requirements.txt file by something similar)

While the build didn't issue any errors, I couldn't figure out where the resulting 'binary' was placed, so I can't use lxdock at the moment.

As I said, I have absolutely no knowledge about the python ecosystem (e.g. 'pip install? why not pip3 install?'), so I think I'll have to wait for a new release. No problem for me, as I'm just playing around.

Thanks!

**Comment by dctremblay** [comment]
+1

**Comment by Shark-Linux** [comment]
Ive held back the newest version of LXD from the SharkLinux distro as lxdock is my personal favorite of all the included tools. That said, any update on this? Its not a huge deal but each repo update that is done I need to manually go in and pull the new lxd deb files before confirming the update.

**Comment by lingxiaoyang** [comment]
@hsoft  I saw that your PR was just merged into pylxd/master. Congrats!

We may then wait for its next release.

**Comment by hsoft** [comment]
Fixed and released in v0.3.0

**Comment by dctremblay** [comment]
Thanks alot pal
